services:
  api:
    build: ./api
    container_name: fastapi_model
    ports:
      - "8000:8000"
    restart: always

  app:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: always